import { useState, useCallback, useMemo } from "react";

const T={bg:"#0B0E0C",surface:"#111512",card:"#161A17",border:"#222926",green:"#52C97A",greenDim:"#1E4A2E",greenGlow:"rgba(82,201,122,0.12)",gold:"#D4A84B",goldDim:"rgba(212,168,75,0.12)",red:"#E05555",redDim:"rgba(224,85,85,0.1)",blue:"#4E9FE5",blueDim:"rgba(78,159,229,0.1)",text:"#EDF2EE",textSub:"#7A9480",textMuted:"#3D5040"};
const WORKERS=["Jose","Ruben","Fernando","Vaquero 1","Vaquero 2","Vaquero 3","Vaquero 4","Diarista 1","Diarista 2"];
const uid=()=>Math.random().toString(36).slice(2,10);
const fmtD=d=>{try{return new Date(d+"T12:00").toLocaleDateString("es-BO",{day:"2-digit",month:"2-digit",year:"numeric"});}catch{return d||"";}};
const today=()=>new Date().toISOString().slice(0,10);

function useLS(key,init){const[data,set]=useState(()=>{try{const s=localStorage.getItem("lp_cal_"+key);return s?JSON.parse(s):init;}catch{return init;}});const save=useCallback(val=>{const next=typeof val==="function"?val(data):val;set(next);try{localStorage.setItem("lp_cal_"+key,JSON.stringify(next));}catch{};},[data,key]);return[data,save];}

function Bdg({color,children,xs}){const map={green:[T.greenGlow,T.green],red:[T.redDim,T.red],blue:[T.blueDim,T.blue],gold:[T.goldDim,T.gold]};const[bg,fg]=map[color]||["rgba(122,148,128,0.1)",T.textSub];return<span style={{padding:xs?"2px 7px":"3px 10px",borderRadius:20,fontSize:xs?10:11,fontWeight:700,background:bg,color:fg,display:"inline-block",lineHeight:1.5}}>{children}</span>;}

function Btn({children,onClick,v="primary",sz="md",full,disabled}){const[h,sh]=useState(false);const p={xs:"5px 10px",sm:"7px 14px",md:"10px 18px"}[sz]||"10px 18px";const fs={xs:10,sm:11,md:13}[sz]||13;const vs={primary:{background:h?"#63D98A":T.green,color:"#091A10"},danger:{background:h?"#E86666":T.red,color:"#fff"},ghost:{background:h?T.border:"transparent",color:T.textSub,border:`1px solid ${T.border}`},warn:{background:h?"rgba(224,85,85,0.2)":T.redDim,color:T.red,border:`1px solid rgba(224,85,85,0.3)`}};return<button style={{padding:p,fontSize:fs,fontWeight:600,borderRadius:10,border:"none",cursor:disabled?"not-allowed":"pointer",display:"inline-flex",alignItems:"center",gap:5,transition:"all 0.15s",width:full?"100%":"auto",justifyContent:full?"center":"flex-start",opacity:disabled?0.5:1,fontFamily:"inherit",...vs[v]}} onClick={onClick} disabled={disabled} onMouseEnter={()=>sh(true)} onMouseLeave={()=>sh(false)}>{children}</button>;}

function Inp({label,value,onChange,type="text",placeholder,required,options,rows}){const s={background:"#0D1210",border:`1px solid ${T.border}`,borderRadius:10,padding:"11px 14px",color:T.text,fontSize:13,width:"100%",outline:"none",fontFamily:"inherit",boxSizing:"border-box"};return<div>{label&&<label style={{fontSize:11,fontWeight:700,color:T.textSub,marginBottom:5,display:"block",textTransform:"uppercase",letterSpacing:"0.6px"}}>{label}{required&&<span style={{color:T.red}}> *</span>}</label>}{options?<select style={s} value={value||""} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o.v!=null?o.v:o} value={o.v!=null?o.v:o}>{o.l!=null?o.l:o}</option>)}</select>:rows?<textarea style={{...s,minHeight:rows*26,resize:"vertical"}} value={value||""} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>:<input style={s} type={type} value={value||""} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</div>;}

function Modal({title,onClose,children}){return<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.82)",zIndex:400,display:"flex",alignItems:"flex-end",justifyContent:"center"}} onClick={onClose}><div style={{background:T.surface,border:`1px solid ${T.border}`,borderRadius:"20px 20px 0 0",padding:"24px 20px 32px",width:"100%",maxWidth:600,maxHeight:"94vh",overflowY:"auto"}} onClick={e=>e.stopPropagation()}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><div style={{fontSize:17,fontWeight:700}}>{title}</div><button onClick={onClose} style={{background:T.border,border:"none",borderRadius:8,width:30,height:30,cursor:"pointer",color:T.textSub,fontSize:15,display:"flex",alignItems:"center",justifyContent:"center"}}>✕</button></div>{children}</div></div>;}

function G2({children,gap=12}){return<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap}}>{children}</div>;}

export default function CalendarioLP(){
  const[actividades,setActividades]=useLS("actividades",[]);
  const[showNew,sNew]=useState(false);
  const[editando,setEditando]=useState(null);
  const[eliminando,setEliminando]=useState(null);
  const[filtro,setFiltro]=useState("proximas");
  const blank={fecha:today(),titulo:"",tipoTrabajo:"",responsable:WORKERS[0],obs:"",estado:"Programado",productos:[{nombre:"",cantidad:"",unidad:"kg"}]};
  const[form,setForm]=useState(blank);
  const f=k=>v=>setForm(p=>({...p,[k]:v}));
  const addProd=()=>setForm(p=>({...p,productos:[...p.productos,{nombre:"",cantidad:"",unidad:"kg"}]}));
  const updProd=(i,k,v)=>setForm(p=>({...p,productos:p.productos.map((pr,idx)=>idx===i?{...pr,[k]:v}:pr)}));
  const delProd=i=>setForm(p=>({...p,productos:p.productos.filter((_,idx)=>idx!==i)}));
  const abrir=(a=null)=>{setEditando(a);setForm(a?{...a,productos:a.productos||[{nombre:"",cantidad:"",unidad:"kg"}]}:blank);sNew(true);};
  const cerrar=()=>{sNew(false);setEditando(null);setForm(blank);};
  const guardar=()=>{if(!form.titulo.trim()||!form.fecha)return alert("Completá fecha y título");if(editando){setActividades(as=>as.map(a=>a.id===editando.id?{...form,id:editando.id}:a));}else{setActividades(as=>[...as,{...form,id:uid(),cAt:new Date().toISOString()}]);}cerrar();};
  const completar=id=>setActividades(as=>as.map(a=>a.id===id?{...a,estado:"Completado"}:a));
  const eliminar=()=>{setActividades(as=>as.filter(a=>a.id!==eliminando.id));setEliminando(null);};
  const hoy=today();
  const filtradas=useMemo(()=>{let res=[...actividades];if(filtro==="proximas")res=res.filter(a=>a.fecha>=hoy&&a.estado==="Programado");else if(filtro==="completadas")res=res.filter(a=>a.estado==="Completado");else if(filtro==="vencidas")res=res.filter(a=>a.fecha<hoy&&a.estado==="Programado");return res.sort((a,b)=>a.fecha>b.fecha?1:-1);},[actividades,filtro,hoy]);
  const proximas=actividades.filter(a=>a.fecha>=hoy&&a.estado==="Programado").length;
  const vencidas=actividades.filter(a=>a.fecha<hoy&&a.estado==="Programado").length;

  return<div>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:20}}>
      <div><div style={{fontSize:20,fontWeight:800,color:T.text}}>Calendario 📅</div><div style={{fontSize:12,color:T.textSub,marginTop:2}}>Trabajos programados</div></div>
      <Btn onClick={()=>abrir()}>+ Nueva Actividad</Btn>
    </div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:16}}>
      {[{l:"Próximas",v:proximas,c:T.blue},{l:"Completadas",v:actividades.filter(a=>a.estado==="Completado").length,c:T.green},{l:"Vencidas",v:vencidas,c:vencidas>0?T.red:T.textMuted}].map(s=><div key={s.l} style={{background:T.card,border:`1px solid ${T.border}`,borderRadius:12,padding:"12px 14px",borderLeft:`3px solid ${s.c}`}}><div style={{fontSize:20,fontWeight:800,color:s.c}}>{s.v}</div><div style={{fontSize:11,color:T.textSub}}>{s.l}</div></div>)}
    </div>
    <div style={{display:"flex",gap:6,marginBottom:16,flexWrap:"wrap"}}>
      {[["proximas","📌 Próximas"],["completadas","✅ Completadas"],["vencidas","⏰ Vencidas"],["todas","📋 Todas"]].map(([k,l])=><button key={k} onClick={()=>setFiltro(k)} style={{padding:"7px 14px",fontSize:12,fontWeight:filtro===k?700:400,color:filtro===k?T.green:T.textSub,borderRadius:20,cursor:"pointer",background:filtro===k?T.greenGlow:"transparent",border:`1px solid ${filtro===k?T.green:T.border}`,fontFamily:"inherit",outline:"none"}}>{l}</button>)}
    </div>
    {filtradas.length===0&&<div style={{textAlign:"center",padding:"48px 20px",color:T.textMuted}}><div style={{fontSize:36,marginBottom:10}}>📅</div><div style={{fontSize:13}}>No hay actividades aquí</div></div>}
    {filtradas.map(a=>{const esVenc=a.fecha<hoy&&a.estado==="Programado";const accent=a.estado==="Completado"?T.green:esVenc?T.red:T.blue;return<div key={a.id} style={{background:T.card,border:`1px solid ${T.border}`,borderRadius:14,padding:"18px",borderLeft:`3px solid ${accent}`,marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}><div style={{flex:1}}><div style={{fontWeight:700,fontSize:15,marginBottom:4}}>{a.titulo}</div>{a.tipoTrabajo&&<div style={{fontSize:13,color:T.textSub,marginBottom:6}}>🔧 {a.tipoTrabajo}</div>}<div style={{display:"flex",gap:6,flexWrap:"wrap"}}><Bdg color={a.estado==="Completado"?"green":esVenc?"red":"blue"}>{a.estado==="Completado"?"✅ Completado":esVenc?"⏰ Vencido":"📌 Programado"}</Bdg><Bdg color="gold">📅 {fmtD(a.fecha)}</Bdg><Bdg color="blue">👤 {a.responsable}</Bdg></div></div></div>{a.obs&&<div style={{fontSize:12,color:T.textSub,marginBottom:8,fontStyle:"italic"}}>{a.obs}</div>}{a.productos?.filter(p=>p.nombre).length>0&&<div style={{marginBottom:8}}><div style={{fontSize:10,color:T.textMuted,marginBottom:4,textTransform:"uppercase",letterSpacing:"0.5px"}}>Productos</div>{a.productos.filter(p=>p.nombre).map((p,i)=><div key={i} style={{fontSize:12,color:T.gold}}>• {p.nombre}{p.cantidad?` — ${p.cantidad} ${p.unidad}`:""}</div>)}</div>}<div style={{display:"flex",gap:6,paddingTop:10,borderTop:`1px solid ${T.border}`}}>{a.estado==="Programado"&&<Btn v="primary" sz="xs" onClick={()=>completar(a.id)}>✓ Completar</Btn>}<Btn v="ghost" sz="xs" onClick={()=>abrir(a)}>✏️ Editar</Btn><Btn v="warn" sz="xs" onClick={()=>setEliminando(a)}>🗑️ Eliminar</Btn></div></div>;})}
    {showNew&&<Modal title={editando?"Editar Actividad":"Nueva Actividad"} onClose={cerrar}><div style={{display:"flex",flexDirection:"column",gap:14}}><Inp label="Título" required value={form.titulo} onChange={f("titulo")} placeholder="Ej: Vacunación Tropa Norte"/><G2><Inp label="Fecha" required type="date" value={form.fecha} onChange={f("fecha")}/><Inp label="Responsable" value={form.responsable} onChange={f("responsable")} options={WORKERS}/></G2><Inp label="Tipo de Trabajo" value={form.tipoTrabajo} onChange={f("tipoTrabajo")} placeholder="Ej: Vacunación, Desparasitación, Herraje, Limpieza..."/><Inp label="Observaciones" value={form.obs} onChange={f("obs")} placeholder="Detalles adicionales..." rows={2}/><div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><label style={{fontSize:11,fontWeight:700,color:T.textSub,textTransform:"uppercase",letterSpacing:"0.6px"}}>Productos a Usar</label><Btn v="ghost" sz="xs" onClick={addProd}>+ Agregar</Btn></div>{form.productos.map((p,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"1fr 80px 80px 30px",gap:6,marginBottom:6,alignItems:"center"}}><input value={p.nombre} onChange={e=>updProd(i,"nombre",e.target.value)} placeholder="Producto" style={{background:"#0D1210",border:`1px solid ${T.border}`,borderRadius:8,padding:"8px 10px",color:T.text,fontSize:12,outline:"none",fontFamily:"inherit"}}/><input value={p.cantidad} onChange={e=>updProd(i,"cantidad",e.target.value)} placeholder="Cant." type="number" style={{background:"#0D1210",border:`1px solid ${T.border}`,borderRadius:8,padding:"8px 10px",color:T.text,fontSize:12,outline:"none",fontFamily:"inherit"}}/><select value={p.unidad} onChange={e=>updProd(i,"unidad",e.target.value)} style={{background:"#0D1210",border:`1px solid ${T.border}`,borderRadius:8,padding:"8px 6px",color:T.text,fontSize:12,outline:"none",fontFamily:"inherit"}}>{["kg","lt","dosis","fardos","bolsas","unid"].map(u=><option key={u}>{u}</option>)}</select><button onClick={()=>delProd(i)} style={{background:T.redDim,border:"none",borderRadius:6,width:28,height:28,cursor:"pointer",color:T.red,fontSize:14,display:"flex",alignItems:"center",justifyContent:"center"}}>✕</button></div>)}</div>{editando&&<Inp label="Estado" value={form.estado} onChange={f("estado")} options={["Programado","Completado"]}/>}<G2><Btn v="ghost" full onClick={cerrar}>Cancelar</Btn><Btn full onClick={guardar}>{editando?"Guardar Cambios":"Crear Actividad"}</Btn></G2></div></Modal>}
    {eliminando&&<Modal title="¿Eliminar?" onClose={()=>setEliminando(null)}><div style={{fontSize:14,color:T.textSub,marginBottom:20}}>¿Eliminar "{eliminando.titulo}"?</div><G2><Btn v="ghost" full onClick={()=>setEliminando(null)}>Cancelar</Btn><Btn v="danger" full onClick={eliminar}>Eliminar</Btn></G2></Modal>}
  </div>;
}
